# pyproject.toml
# This file is used ONLY for tool configurations.
# Dependencies are managed via requirements.txt and requirements-dev.txt.

[tool.ruff]
line-length = 200 # Or your preferred line length

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B", "UP", "PT", "SIM"]
ignore = []
# fixable = ["ALL"] # Optional: if you want ruff pre-commit hook to fix everything it can

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.8" # Or your target Python version
warn_return_any = true
warn_unused_configs = true
plugins = ["numpy.typing.mypy_plugin"] # If using numpy
# If your code is in src/: mypy_path = "src"
# If your code is at the root: mypy_path = "." (or omit if Mypy finds it)

[tool.pytest.ini_options]
minversion = "6.0"
# addopts can be used for default options if you run pytest manually
# e.g., addopts = "-ra -q"
# Coverage will be typically driven by the CI script or Makefile
testpaths = ["tests"] # If you have a tests directory

[tool.bandit]
# Bandit specific configurations (e.g., skips, severity levels) can go here.
# Example:
# skips = ["B101"] # Skip the assert_used check
# severity_medium_score = 2.0